#include "nsISupports.idl"

interface nsIArray;
interface nsAString;

[scriptable, uuid(b23e4e97-4e78-4da5-bf18-1accf19361db)]
interface nsISPRS_PKCS11_Wrapper : nsISupports
{

  //Utility Functions
  long SPRS_getLastError();
	
  boolean SPRS_initCrypto();
  void SPRS_finalizeCrypto();
  void SPRS_enumerateCards(out PRUint32 count, [retval, array, size_is(count)] out string cards);
	void getArray(out unsigned long count, [array, size_is(count),retval] out long retv);
	
  boolean SPRS_selectCard(in long card, in AString pin);
  void SPRS_listCerts(out PRUint32 count, [retval, array, size_is(count)] out string certs);
  boolean SPRS_createCert(in AString cert);

  //File Functions
  boolean SPRS_encryptFile(in AString input_file, in AString output_file, in AString cert);
  boolean SPRS_signFile(in AString input_file, in AString output_file, in AString cert);
  nsAString SPRS_decrypt(in AString input_file);
  nsAString SPRS_verify(in AString input_file);
	boolean SPRS_loadFile(in AString input_file, out AString output);
  
	//stuff not in the wrapper API
	long SPRS_getTokenCount();
};

